version: "3.9"
services:
  db:
    image: postgres:16
    container_name: rentatrolley_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: rentatrolley_backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run start:prod

volumes:
  postgres_data:
