# .github/workflows/deploy.yml

name: Deploy Backend to Contabo

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          BRANCH=${{ github.ref_name }}

          if [ "$BRANCH" == "main" ]; then
            REMOTE_SCRIPT="./run-prod.sh"
          elif [ "$BRANCH" == "dev" ]; then
            REMOTE_SCRIPT="./run-dev.sh"
          else
            echo "No deploy script for branch $BRANCH"
            exit 1
          fi

          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.PROJECT_PATH }} && git pull origin $BRANCH && chmod +x $REMOTE_SCRIPT && $REMOTE_SCRIPT"
